# docker-compose.yml
version: "3.8"

services:
  bot:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    platform: linux/amd64 # arm64 # For M2 Mac
    restart: unless-stopped
    mem_limit: 2g
    memswap_limit: 2g
